his is the ultimate test!

$current.name$

From Address $from_addr$ 
To Address $to_addr$ 
Dear $to$,
    Permit me to inform you of my desire of going into business relationship with you. I have
    the believe you are a reputable and responsible and trustworthy person I can do business
    with from the little information so far I gathered about you during my search for a partner
    and by matter of trust I must not hesitate to confide in you for this simple and sincere business
. ... 
Best Regards, $from$
$toto$
